name: Submodule Sync
on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch: ~

jobs:
  submodule-sync:
    name: Submodule Sync
    runs-on: ubuntu-latest
    steps:
      - name: Submodule Sync
        uses: mheap/submodule-sync-action@v1
        with:
          path: Experiment
          ref: main
          pr_branch: automated-submodule-update
          target_branch: main